#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.                                                                   
apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*
echo "frontend my_frontend
   bind *:80
   mode http
   default_backend my_backend" >> /etc/haproxy/haproxy.cfg
echo "backend my_backend
   balance roundrobin
   server 2821-web-01 34.75.191.53:80 check
   server 2821-web-02 3.94.192.73:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
