#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 with the FizzBuzz rules.

counter=1
while [ $counter -le 100 ]
do
	if [ $(( counter % 15 )) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( counter % 3 )) -eq 0 ]
	then
		echo "Buzz"
	elif [ $(( counter % 5 )) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$counter"
	fi
	((counter++))
done
