#!/usr/bin/env bash
# Fix this container 
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod -R 777 /etc/nginx/
sudo -u nginx service nginx start
